// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224105250_PitchesData")]
    partial class PitchesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PitchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PitchId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Domain.Entities.Pitch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pitches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Index = 1
                        },
                        new
                        {
                            Id = 2,
                            Index = 2
                        },
                        new
                        {
                            Id = 3,
                            Index = 3
                        },
                        new
                        {
                            Id = 4,
                            Index = 4
                        },
                        new
                        {
                            Id = 5,
                            Index = 5
                        },
                        new
                        {
                            Id = 6,
                            Index = 6
                        },
                        new
                        {
                            Id = 7,
                            Index = 7
                        },
                        new
                        {
                            Id = 8,
                            Index = 8
                        },
                        new
                        {
                            Id = 9,
                            Index = 9
                        },
                        new
                        {
                            Id = 10,
                            Index = 10
                        },
                        new
                        {
                            Id = 11,
                            Index = 11
                        },
                        new
                        {
                            Id = 12,
                            Index = 12
                        },
                        new
                        {
                            Id = 13,
                            Index = 13
                        },
                        new
                        {
                            Id = 14,
                            Index = 14
                        },
                        new
                        {
                            Id = 15,
                            Index = 15
                        },
                        new
                        {
                            Id = 16,
                            Index = 16
                        },
                        new
                        {
                            Id = 17,
                            Index = 17
                        },
                        new
                        {
                            Id = 18,
                            Index = 18
                        },
                        new
                        {
                            Id = 19,
                            Index = 19
                        },
                        new
                        {
                            Id = 20,
                            Index = 20
                        },
                        new
                        {
                            Id = 21,
                            Index = 21
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.HasOne("Domain.Entities.Pitch", "Pitch")
                        .WithMany()
                        .HasForeignKey("PitchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pitch");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
